# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: koala bear
email: vanderliang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    观水有术，必观其澜，日月有明，容光必照。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wsfdl.com" # the base hostname & protocol for your site
github_username:  deliangfan

# Build settings
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids:      true
  auto_id_prefix: 'id-'
  # footnote_nr:   1
  # entity_output: as_char
  # toc_levels:    1..6
  # smart_quotes:  lsquo,rsquo,ldquo,rdquo
  # use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style
